### PR TITLE
Update 07-04-2020

### PR DESCRIPTION
**Pull request by smgoldsmithmsdc**

### CODE REVIEW

**Comment by jhackett1** [comment]
well well, what's all this then!

**Comment by smgoldsmithmsdc** [comment]
Hi Jaye,

Looking at using the excellent project code 😊

Managed to quickly get a test site up and running

https://msdc-coronavirus-service-dir.herokuapp.com/

The only thing I’m having issues with is the distance

<small class="service-card__distance"><%= s.rough_distance %></small>

Any thoughts or pointers would be welcome

Kind regards
Steve

Steve Goldsmith CITP MBCS
Digital and Technology
Web and Digital Content Officer
01444 477189
steve.goldsmith@midsussex.gov.uk<mailto:steve.goldsmith@midsussex.gov.uk>
www.midsussex.gov.uk<http://www.midsussex.gov.uk/>

Working Together for a Better Mid Sussex

**Comment by smgoldsmithmsdc** [comment]
From: Steve Goldsmith
Sent: 09 April 2020 16:50
To: wearefuturegov/coronavirus-service-directory <reply@reply.github.com>; wearefuturegov/coronavirus-service-directory <coronavirus-service-directory@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [wearefuturegov/coronavirus-service-directory] Update 07-04-2020 (#6)

Hi Jaye,

Looking at using the excellent project code 😊

Managed to quickly get a test site up and running

https://msdc-coronavirus-service-dir.herokuapp.com/

The only thing I’m having issues with is the distance

<small class="service-card__distance"><%= s.rough_distance %></small>

Any thoughts or pointers would be welcome

Kind regards
Steve

Steve Goldsmith CITP MBCS
Digital and Technology
Web and Digital Content Officer
01444 477189
steve.goldsmith@midsussex.gov.uk<mailto:steve.goldsmith@midsussex.gov.uk>
www.midsussex.gov.uk<http://www.midsussex.gov.uk/>

Working Together for a Better Mid Sussex

**Comment by jhackett1** [comment]
hello! `rough_distance` is defined [here](https://github.com/wearefuturegov/coronavirus-service-directory/blob/master/app/models/service.rb#L5).

when you do a search, it calculates a distance value in miles for every service and makes it available as a key called `distance`. all `rough_distance` is doing is taking the computed distance value and turning it into something a bit friendlier for users.

as long as your list of services has been geocoded correctly (you'll need an api key for [google's geocoding service](https://developers.google.com/maps/documentation/geocoding/intro), or to [change the config to use a different geocoding service](https://github.com/wearefuturegov/coronavirus-service-directory/blob/master/config/initializers/geocoder.rb)) and have latitude and longitude values when you look in the database, distances _should_ just appear in the results.

**Comment by smgoldsmithmsdc** [comment]
Hi Jaye,

Thanks for the support, still no distance in the results.

I’ve checked the database and the lat/lon are correct.

Any thoughts?

Regards
Steve

**Comment by AndyICT2U** [comment]
Hi Steve,
We're replicating and building a version too in Lewisham so digging around in that area. I got caught out by the handling of the 'recommended' field in the database. I was thinking of it as a 'verification of authenticity' type field so had them all set to true, in which case the distance doesn't appear in the search results summary boxes.
Cheers
Andy

**Comment by smgoldsmithmsdc** [comment]
Hi Andy,

Thanks for the pointer your correct the recommended field defaults to true on import. Switch to false the distance shows.

Hope the Lewisham version is coming along look forward to viewing.

Hope to have a version up and running soon.

Thanks Again
Steve

Steve Goldsmith CITP MBCS
Digital and Technology
Web and Digital Content Officer
01444 477189
steve.goldsmith@midsussex.gov.uk<mailto:steve.goldsmith@midsussex.gov.uk>
www.midsussex.gov.uk<http://www.midsussex.gov.uk/>

Working Together for a Better Mid Sussex

**Pull request closed without merging**
